# Generated by Django 4.1.7 on 2023-03-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.CharField(max_length=8192)),
                ('answer_text', models.CharField(max_length=8192)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
